// <auto-generated />
using GameNite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameNite.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20230426135850_DBCreation")]
    partial class DBCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameNite.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OnHand")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("InventoryId");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            InventoryId = 1,
                            ItemName = "Chessex Nebula Polyhedral Dice Set Wisteria with White Luminary (7 dice)",
                            OnHand = 7,
                            Price = 11.99
                        },
                        new
                        {
                            InventoryId = 2,
                            ItemName = "Call of Cthulhu Keeper's Handbook",
                            OnHand = 3,
                            Price = 46.990000000000002
                        },
                        new
                        {
                            InventoryId = 3,
                            ItemName = "Fluxx",
                            OnHand = 13,
                            Price = 5.9900000000000002
                        },
                        new
                        {
                            InventoryId = 4,
                            ItemName = "Catan",
                            OnHand = 2,
                            Price = 61.990000000000002
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
