// <auto-generated />
using GameNite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameNite.Migrations
{
    [DbContext(typeof(InventoryContext))]
    partial class InventoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameNite.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OnHand")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("InventoryId");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            InventoryId = 1,
                            ItemName = "Chessex Nebula Polyhedral Dice Set Wisteria with White Luminary (7 dice)",
                            ItemType = "Accessory",
                            OnHand = 7,
                            Price = 11.99,
                            Quantity = 0
                        },
                        new
                        {
                            InventoryId = 2,
                            ItemName = "Call of Cthulhu Keeper's Handbook",
                            ItemType = "Book",
                            OnHand = 3,
                            Price = 46.990000000000002,
                            Quantity = 0
                        },
                        new
                        {
                            InventoryId = 3,
                            ItemName = "Fluxx",
                            ItemType = "Card Game",
                            OnHand = 13,
                            Price = 5.9900000000000002,
                            Quantity = 0
                        },
                        new
                        {
                            InventoryId = 4,
                            ItemName = "Catan",
                            ItemType = "Board Game",
                            OnHand = 2,
                            Price = 61.990000000000002,
                            Quantity = 0
                        },
                        new
                        {
                            InventoryId = 5,
                            ItemName = "Battletech Salavage Box",
                            ItemType = "Accessory",
                            OnHand = 25,
                            Price = 5.9900000000000002,
                            Quantity = 0
                        },
                        new
                        {
                            InventoryId = 6,
                            ItemName = "Betrayal at House on the Hill",
                            ItemType = "Board Game",
                            OnHand = 2,
                            Price = 59.990000000000002,
                            Quantity = 0
                        },
                        new
                        {
                            InventoryId = 7,
                            ItemName = "CandyLand",
                            ItemType = "Board Game",
                            OnHand = 1,
                            Price = 30.0,
                            Quantity = 0
                        },
                        new
                        {
                            InventoryId = 8,
                            ItemName = "Coup",
                            ItemType = "Card Game",
                            OnHand = 5,
                            Price = 15.99,
                            Quantity = 0
                        },
                        new
                        {
                            InventoryId = 9,
                            ItemName = "Dice Bag",
                            ItemType = "Accessory",
                            OnHand = 14,
                            Price = 21.989999999999998,
                            Quantity = 0
                        },
                        new
                        {
                            InventoryId = 10,
                            ItemName = "Dice Tray",
                            ItemType = "Accessory",
                            OnHand = 12,
                            Price = 14.99,
                            Quantity = 0
                        },
                        new
                        {
                            InventoryId = 11,
                            ItemName = "Dragon Shield",
                            ItemType = "Accessory",
                            OnHand = 14,
                            Price = 21.989999999999998,
                            Quantity = 0
                        },
                        new
                        {
                            InventoryId = 12,
                            ItemName = "Edge of the Empire",
                            ItemType = "Book",
                            OnHand = 3,
                            Price = 55.990000000000002,
                            Quantity = 0
                        },
                        new
                        {
                            InventoryId = 13,
                            ItemName = "Eldritch Horror",
                            ItemType = "Board Game",
                            OnHand = 1,
                            Price = 65.989999999999995,
                            Quantity = 0
                        },
                        new
                        {
                            InventoryId = 14,
                            ItemName = "Gloom",
                            ItemType = "Card Game",
                            OnHand = 5,
                            Price = 21.989999999999998,
                            Quantity = 0
                        },
                        new
                        {
                            InventoryId = 15,
                            ItemName = "Hunter the Reckoning",
                            ItemType = "Book",
                            OnHand = 3,
                            Price = 65.989999999999995,
                            Quantity = 0
                        },
                        new
                        {
                            InventoryId = 16,
                            ItemName = "Magic The Gathering Pack",
                            ItemType = "Card Game",
                            OnHand = 35,
                            Price = 5.9900000000000002,
                            Quantity = 0
                        },
                        new
                        {
                            InventoryId = 17,
                            ItemName = "Pathfinder 2e Core Rulebook",
                            ItemType = "Book",
                            OnHand = 5,
                            Price = 59.990000000000002,
                            Quantity = 0
                        },
                        new
                        {
                            InventoryId = 18,
                            ItemName = "Pokemon Silver Tempest Packs",
                            ItemType = "Card Game",
                            OnHand = 26,
                            Price = 5.9900000000000002,
                            Quantity = 0
                        },
                        new
                        {
                            InventoryId = 19,
                            ItemName = "Red Dragon Inn",
                            ItemType = "Board Game",
                            OnHand = 4,
                            Price = 65.989999999999995,
                            Quantity = 0
                        },
                        new
                        {
                            InventoryId = 20,
                            ItemName = "Scion Demigod",
                            ItemType = "Book",
                            OnHand = 1,
                            Price = 62.990000000000002,
                            Quantity = 0
                        },
                        new
                        {
                            InventoryId = 21,
                            ItemName = "Sentinel Comics Core Rulebook",
                            ItemType = "Book",
                            OnHand = 6,
                            Price = 49.990000000000002,
                            Quantity = 0
                        },
                        new
                        {
                            InventoryId = 22,
                            ItemName = "Warhammer Paintset",
                            ItemType = "Accessory",
                            OnHand = 1,
                            Price = 75.989999999999995,
                            Quantity = 0
                        },
                        new
                        {
                            InventoryId = 23,
                            ItemName = "One Night Ultimate Werewolf",
                            ItemType = "Card Game",
                            OnHand = 3,
                            Price = 29.989999999999998,
                            Quantity = 0
                        },
                        new
                        {
                            InventoryId = 24,
                            ItemName = "Zombiecide",
                            ItemType = "Board Game",
                            OnHand = 1,
                            Price = 89.989999999999995,
                            Quantity = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
